### ISSUE TITLE
"no suitable driver found" - RHEL6, Oracle

### ISSUE THREAD

**Issue by sgcarson** [nutztherookie/JayDeBeApi3#1]
Thank you very much for porting this package to Python 3! I am trying to use it to connect to an Oracle database using the same JDBC drivers that the Java developers around here use. I am working on Red Hat Enterprise Linux v6, Python 3.3. I downloaded and installed the following packages:

JPype1-py3-0.5.5.2.tar.gz:
  https://pypi.python.org/pypi/JPype1-py3/0.5.5.2

JayDeBeApi3-1.2.tar.gz:
  https://pypi.python.org/pypi/JayDeBeApi3/1.2

I installed them in a place I will call "<install_dir>"; I then put "<install_dir>" on PYTHONPATH:

printenv PYTHONPATH
<install_dir>:/tools/python_libs/lib/site-packages

In my environment "JAVA_HOME" is not set, so I used the third argument to jaydebeapi.connect() and set it to the location of the "ojdbc6_g.jar" driver:

/tools/oracle/client/product/current/client_1/jdbc/lib/ojdbc6_g.jar

I verified that CLASSPATH is set as follows:

printenv CLASSPATH
  /lasp/apps/db_tools/share/java/idldb.jar:
  /tools/oracle/client/product/current/client_1/jdbc/lib/ojdbc6_g.jar:
  /tools/sybase-client/jConnect/classes/jconn3.jar

 Here is how I am trying to get a connection:

import jaydebeapi

cnxn = \
jaydebeapi.connect( \
  'oracle.jdbc.driver.OracleDriver', \
  ['jdbc:oracle:thin:@mms-db:1521/mms-db', '<username>', '<password>'], \
  '/tools/oracle/client/product/current/client_1/jdbc/lib/ojdbc6_g.jar')

And here is the error message I am getting:

{noformat}
python3 test_conn.py
Traceback (most recent call last):
  File "test_conn.py", line 9, in <module>
    '/tools/oracle/client/product/current/client_1/jdbc/lib/ojdbc6_g.jar' \
  File "/home/stca2567/svn/OSW/multi-mission/poda/trunk/src/JayDeBeApi/install/lib/python3.3/site-packages/JayDeBeApi3-1.2-py3.3.egg/jaydebeapi/__init__.py", line 63, in connect
  File "/home/stca2567/svn/OSW/multi-mission/poda/trunk/src/JayDeBeApi/install/lib/python3.3/site-packages/py4j-0.8.2.1-py3.3.egg/py4j/java_gateway.py", line 538, in __call__
    self.target_id, self.name)
  File "/home/stca2567/svn/OSW/multi-mission/poda/trunk/src/JayDeBeApi/install/lib/python3.3/site-packages/py4j-0.8.2.1-py3.3.egg/py4j/protocol.py", line 300, in get_return_value
    format(target_id, '.', name), value)
py4j.protocol.Py4JJavaError: An error occurred while calling z:java.sql.DriverManager.getConnection.
: java.sql.SQLException: No suitable driver found for jdbc:oracle:thin:@mms-db:1521/mms-db
	at java.sql.DriverManager.getConnection(DriverManager.java:635)
	at java.sql.DriverManager.getConnection(DriverManager.java:195)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:622)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:231)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:379)
	at py4j.Gateway.invoke(Gateway.java:259)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:133)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.GatewayConnection.run(GatewayConnection.java:207)
	at java.lang.Thread.run(Thread.java:701)
{noformat}

I am not a Java programmer so I am a little lost here - can you spot anything I am doing wrong? Thanks for your help!

**Comment by nutztherookie** [comment]
As I've never ever used Oracle before I'm not really sure what's the problem.

However Django for example supports Oracle and they apparently use http://cx-oracle.sourceforge.net/ . Do you really want to go with an extra JDBC layer?

**Comment by sgcarson** [comment]
Thanks so much for your reply!

The reason I am interested in trying to use JDBC from Python is as follows. We are storing science data in a BLOB field in Oracle. I have written a Python code that allows users to specify the data they want without having to know SQL. I am using "pyodbc" for my database connection. After people started using my code they complained that the throughput - i.e. the number of bytes per second - was very low. There are a couple of other developers here that use Java to access Oracle using JDBC. I had them submit my "test query" with thier codes and they found that they could retrieve BLOB information 10x faster with JDBC than I could with "pyodbc". There was also another developer using Python with cx_Oracle - he obtained the same (slow) throughput rates that I did, even though he was using "cx_Oracle" instead of "pyodbc".

I then did an experiment with my code to retrieve something *other* than BLOB data (a NUMBER(16,0) field) and that data was returned about 5x faster than BLOB data. So it seems there is a problem with the Oracle-supplied drivers that are part of the Oracle client libraries.

Here is my understanding of how this works:

Python code (using "pyodbc"):
[Oracle DB]<-->[Oracle client lib]<-->[ODBC]<-->[pyodbc]<-->[Python code]

Python code (using cx_Oracle)
[Oracle DB]<-->[Oracle client lib]<-->[ODBC]<-->[cx_Oracle]<-->[Python code]

Java code:
[Oracle DB]<-->[JDBC]<-->[Java code]

So JDBC does not depend on the Oracle client libs and it is 10x faster at handling BLOB data than the Oracle client libs. That is why I am trying to find a way (if possible) to use JDBC from Python. Based on some experiments performed by one of our Java developers I believe what is going on is that the Oracle client libs are dynamically allocating a buffer for each and every BLOB that gets retrieved while the JDBC code uses a statically allocated buffer which gets re-used for every BLOB, and while this means more work for the programmer (who must figure out how long the BLOB actually was and then transfer *only* the data from that BLOB) it means the code runs much faster. Apparently Oracle does not care that much about those of us who must use their client libraries - I think their attitude is you should be using Java (since of course that is now their product as well since they bought out Sun years ago...)

Anyway, sorry to go on so long. Thank you very much for porting "JayDeBeApi" to Python 3. Any thoughts or advice you may have are most welcome!

**Comment by nutztherookie** [comment]
i'm actually sick right now. if you can wait a few more days, i shall look into it, once i'm better. 
it's definitely a solvable issue ;)

**Comment by sgcarson** [comment]
Andreas - no worries! Please relax, take care of yourself and get better!

We are currently using another program (in Scala - using JDBC) as a workaround so this is not a crisis. However we would like to eventually be able to use my code - and Python in general - to retrieve BLOB and all other kinds of data at speeds comparable to other languages (like Java). Your package is the most promising alternative I have found so far, so any insight or assistance you can lend will be gratefully appreciated. :)

**Comment by nutztherookie** [comment]
@sgcarson i think this should've fixed it. i definitely get a more promissing 
`IO Error: The Network Adapter could not establish the connection`, which I think points to the initial setup working.

let me know if there are still problems

**Comment by sgcarson** [comment]
Andreas;

Thank you very much for looking in to this so quickly! Turns out I have 
to work on something else today (and maybe tomorrow) but I will try out 
your changes as soon as I can.

Also: I will be on vacation May 1-11 so if you do not hear from me for a 
while, that is why. I will certainly still be interested in JayDeBeApi 
when I return!

Steve

**Comment by sgcarson** [comment]
Andreas;

It works! Just wanted to let you know I was able to build and use your latest JayDeBeApi3. I can run it on our Solaris machine... but...

In order to use JayDeBeApi3 I needed to install "JPype1-py3". I was able to build JPype1-py3 on our Red Hat machine but not on our Solaris machine. However when I try to run JayDeBeApi3/Jpype1-py3 on our Red Hat machine I still get the error:

No suitable driver found for jdbc:oracle:thin:@<db-name>:1521:<service>

The strange thing is, if I then run on Solaris the JayDeBeApi3/JPype1-py3 that I built on Red Hat, it works fine! That is, I am able to connect to my database and make queries. (Now I have to deal with the fact that the "JavaObject" I get for my query result "does not support the buffer interface"...)

Anyway, thanks for all your help with this! Still not sure why I cannot run it on Red Hat - if you have any ideas of what the problem might be, let me know!

**Comment by sgcarson** [comment]
(tried to edit my previous comment, but for some reason cannot...)

I meant to add when I try to build JPype1-py3 on Solaris I get the error message:

"No Java/JDK could be found - I looked in the following directories:"
/usr/java/LICENSE
/usr/java/sample
/usr/java/jre
/usr/java/bin
/usr/java/lib
/usr/java/THIRDPARTYLICENSEREADME.txt
/usr/java/src.zip
/usr/java/demo
/usr/java/README.html
/usr/java/include
/usr/java/COPYRIGHT
/usr/java/man

Please check that you have it installed.

So anyway, I will look into that and see if I can figure out where JDK is on our Red Hat box...

**Comment by nutztherookie** [comment]
Hey Steve,

something's definitely weird - the latest JayDeBeApi does not use jpype anymore, it uses py4j .. are you sure you're using the latest version?

**Comment by sgcarson** [comment]
Andreas - Thanks for noticing I was using the wrong package to support JayDeBeApi! I will install "py4j" and try my testing again. I talked with one of our other developers and he thinks the problem is simply that JDK is located in a different place on our Solaris servers than on our Red Hat servers.

I am actually glad that I need to use "py4j" instead of "JPype" - my initial testing with "JayDeBeApi3" and "JPype1-py3" showed that it was no faster than "pyodbc" for retrieving BLOB data (in fact it was a lot SLOWER!). This performance problem may have to do with the way I was using the functions in JayDeBeApi or it may be due to "JPype1-py3", or maybe both. I will try this again with "py4j".

Thanks again for the help. It is great to have your advice since you are experienced with this package and I am not!

**Comment by nutztherookie** [comment]
:) no problem, just let me know if there's something i can help with

**Comment by nutztherookie** [comment]
Hey @sgcarson, I'm guessing this is done? Gonna close. Reopen if necessary
